### ISSUE TITLE
Types with formats

### ISSUE THREAD

**Issue by valentinedwv** [wolverdude/GenSON#1]
Tried to use 
!!timestamp "2015-01-01T00:30:00.9Z"
Tossed an error. Added types to the JS_TYPES 

I think this would map to a string with a format of 'date-time'

"aaa": {
            "type": "string",
            "format": "date-time"
        }

**Comment by wolverdude** [comment]
This only supports JSON-serializeable types. Though you're right. It would be a nice feature to be able to extend it.

**Comment by wolverdude** [comment]
There is no reason to implement custom types because JSON-Schema itself (and JSON, for that matter) does not have custom types. The `format` key is useful a useful feature, but it is optional and many validators do not include it.

I'll consider it for the future, but I think `format` is beyond the scope of this project at this point.
