### ISSUE TITLE
Missing 'items' property when adding an Array to an Object schema

### ISSUE THREAD

**Issue by regisoc** [wolverdude/GenSON#16]
Hi @wolverdude,

Your lib is great. I am actually testing/pushing it.
I am currently struggling a bit on this probleme when using a big volume of data from 
[NCBI FTP](https://ftp.ncbi.nlm.nih.gov/pubmed/baseline) (~50Gb). 

Basically, I encounter these kind of data I tried to parse:

```python
if __name__ == "__main__":

  def log(s):
    print(s.to_dict()["properties"]["PubmedData"]["properties"]["ArticleIdList"]["properties"]["ArticleId"])

  s = Schema()

  json_data = {
    "PubmedData": {
      "ArticleIdList": {
        "ArticleId": {
          "@IdType": "pubmed",
          "#text": 152435
        }
      }
    }
  }

  s.add_object(json_data)
  log(s)

  json_data = {
    "PubmedData": {
      "ArticleIdList": {
        "ArticleId": [{
          "@IdType": "pubmed",
          "#text": 'abcd'
        }, {
          "@IdType": "doi",
          "#text": "s;dlfklkxhdflk"
        }]
      }
    }
  }

  s.add_object(json_data)
  print('---')
  log(s)

```
Output:
``` python
{
  'required': ['#text', '@IdType'], 
  'properties': {
    '#text': {'type': 'integer'}, 
    '@IdType': {'type': 'string'}
  }, 
  'type': 'object'
}
  
---
{
  'required': ['#text', '@IdType'], 
  'properties': {
    '#text': {'type': 'integer'}, 
    '@IdType': {'type': 'string'}
  }, 
  'type': ['array', 'object']
}
```

As you can see, the interesting part is on the `#text` property.
Even if the main `type` attribute is updated, the sub-property `#text.type` attribute doenot update as expected.

I was hoping something like that:

```python
{
  'required': ['#text', '@IdType'], 
  'properties': {
    '#text': {'type': ['integer', 'string']}, 
    '@IdType': {'type': 'string'}
  }, 
  'type': ['array', 'object']
}
```

I am kind of new on processing JSON Schema, so do I miss something?

**Comment by wolverdude** [comment]
Good catch. That is _not_ how the schema should look. That said, neither is your expectation. The result is missing the `items` key, and should look like this:

```json
{
  "required": ["#text", "@IdType"], 
  "properties": {
    "#text": {"type": ["integer", "string"]}, 
    "@IdType": {"type": "string"}
  },
  "items": [{
    "required": ["#text", "@IdType"], 
    "properties": {
      "#text": {"type": "integer"}, 
      "@IdType": {"type": "string"}
    }, 
    "type": "object"
  }],
  "type": ["array", "object"]
}
```

However, this is still bad in my opinion because it's hard to understand. Array and Object schemas are structurally different, and mixing them together makes things muddier, not clearer. Ideally, the schema would separate the two using `anyOf`:

```json
{
  "anyOf": [{
    "required": ["#text", "@IdType"], 
    "properties": {
      "#text": {"type": ["integer", "string"]}, 
      "@IdType": {"type": "string"}
    },
    "type": "object"
  },
  {
    "items": [{
      "required": ["#text", "@IdType"], 
      "properties": {
        "#text": {"type": "integer"}, 
        "@IdType": {"type": "string"}
      }, 
      "type": "object"
    }],
    "type": "array"
  }]
}
```

Unfortunately, the current version does not support `anyOf`. The next version will... whenever I get around to releasing it. (As it turns out, `anyOf`, is the main blocker for the new release.)

Regarding your 50GB data dumps, you probably don't need to process all of that data. I would suggest sampling objects at random from various parts of the data block instead of processing the entire thing. The generated schema should cover the vast majority of cases after parsing just a few dozen objects, provided that they are representative of the rest.

**Comment by wolverdude** [comment]
`"anyOf"` is now live in version 1.
