### ISSUE TITLE
Inconsistent handling of `required` list

### ISSUE THREAD

**Issue by krdln** [wolverdude/GenSON#25]
Consider two schemas:

**foo-schema:**
```json
{
  "$schema": "http://json-schema.org/schema#",
  "required": [
    "foo"
  ],
  "type": "object",
  "properties": {
    "foo": {
      "type": "integer"
    }
  }
}
```

<details>
<summary>and analoguous with <emph>bar</emph> field – <strong>bar-schema</strong>
</summary>

```json
{
  "$schema": "http://json-schema.org/schema#",
  "required": [
    "bar"
  ],
  "type": "object",
  "properties": {
    "bar": {
      "type": "integer"
    }
  }
}
```

</details>

When we attempt to merge them, all fields becomes optional. It seems that genson tries to optimize that case by omitting `"required": []`.
```sh
/tmp> genson -s foo-schema -s bar-schema | jq
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "foo": {
      "type": "integer"
    },
    "bar": {
      "type": "integer"
    }
  }
}
```

Let's save it as **foobar-schema**. If we try to merge it once again with **foo-schema**, we should expect  no change (because _merge(foo, bar, foo)_ should be equivalent to _merge(foo, bar)_), but for our surprise, we see that `foo` field is marked as required!
```sh
/tmp> genson -s foobar-schema -s foo-schema | jq
{
  "$schema": "http://json-schema.org/schema#",
  "required": [
    "foo"
  ],
  "type": "object",
  "properties": {
    "foo": {
      "type": "integer"
    },
    "bar": {
      "type": "integer"
    }
  }
}
```

I'm not sure whether lack of `required` field should be interpreted as "we don't know what's required" or "nothing is required" (I guess the latter though), but it'd be great for genson to handle it consistently :)

**Comment by wolverdude** [comment]
Okay, never mind. I realize now that there is a very real reason for this behavior, and it has to do with seed schemas. And yeah, it'll get you into some non-intuitive situations.

The correct behavior under **Rule 2** would be to nix any `required` properties as soon as it encounters a schema without a `required` field. However, this would mean that you would need to explicitly list all the required properties of any object you use in a seed schema. The compromise I came to was to only takes a schema's `required` properties into account if it explicitly lists them. Because the generator's output is lazy and leaves off the `required` key if there are no required properties, when you feed that generated schema back in, you lose the information that `required` had previously been empty, not missing.

I will definitely add docs about this to the README. I think it might also make sense to include an empty `required` key on the result whenever it has been computed to be empty instead of just being ignored completely.

@krdln, will that solve your problem? Would you prefer to add the empty `required` key to the output or keep the existing behavior?

**Comment by wolverdude** [comment]
[Version 1.1.0](https://pypi.org/project/genson/1.1.0/) is now live. Please let me know if you have any more issues.
