### ISSUE TITLE
Merge of complex schemas should use anyOf

### ISSUE THREAD

**Issue by eliasdorneles** [wolverdude/GenSON#3]
Currently, the behavior for schemas with multiple types is to merge everything and use a list of types.

```
>>> s = Schema()
>>> s.add_schema({'type': 'string', 'maxLength': 5}).add_schema({'type': 'number', 'minimum': 0}).to_dict()
{'maxLength': 5, 'minimum': 0, 'type': ['number', 'string']}
```

The expected would be to combine with [anyOf](http://spacetelescope.github.io/understanding-json-schema/reference/combining.html):

```
>>> s = Schema()
>>> s.add_schema({'type': 'string', 'maxLength': 5}).add_schema({'type': 'number', 'minimum': 0}).to_dict()
{'anyOf': [{'type': 'string', 'maxLength': 5}, {'type': 'number', 'minimum': 0}]}
```

One option would be to just always use `anyOf`, regardless if the schema is complex or simple, but it's cool to have the simple array of types when the schemas are simple.

Thoughts?

**Comment by wolverdude** [comment]
This is a good idea. Though we can get the best of both worlds if we only organize it into an `anyOf` structure if other keywords are present. Otherwise we can stick to type arrays for simple schemas.

That being said, the current version only supports the keywords `"type"`, `"items"`, `"properties"` and `"required"`, and adding any logic around other keywords would require a refactor and at least a minor version bump.

**Comment by eliasdorneles** [comment]
> we can get the best of both worlds if we only organize it into an anyOf structure if other keywords are present

Yeah, sounds a good behavior to me.

> the current version only supports the keywords "type", "items", "properties" and "required"

Hmm yeah, I see it's ignoring any other keyword: https://github.com/wolverdude/GenSON/blob/master/genson/generator.py#L63

This sounds like a separate bug, since it's not accepting other valid schemas (with fields like description or validation constraints). Also, as I understand the JSON schema format is meant to be extensible.
It would be nice apply Postel's law here (be conservative with the output, be liberal with the input).

Maybe copying unknown keywords would be a good fallback behavior.

What do you think?

**Comment by wolverdude** [comment]
Copying unknown keywords is exactly what it does, but of course that results in the behavior you mentioned above where it puts two contradictory constraints together because it doesn't know their meaning. Having more advanced logic would be nice, but I'm okay with this for now because it's mostly meant as an easy way to generate basic schemas that you can tweak later.

The line you point to is where it checks to be sure that the two schemas don't have contradictory values for the unknown keyword... which I'm now noticing throws a completely unhelpful the error message. I should make that a little more descriptive.

**Comment by eliasdorneles** [comment]
Oh, you're right, I should've read it more carefully! =)

> Having more advanced logic would be nice, but I'm okay with this for now because it's mostly meant as an easy way to generate basic schemas that you can tweak later.

Agreed, simply copying works well -- even throwing an exception for the conflicting may be too harsh, probably just warning would be enough. :+1:

**Comment by wolverdude** [comment]
The nondescript incompatibility error has been improved and downgraded to a warning in [Genson 0.2.0](https://pypi.python.org/pypi/genson/0.2.0).
