### ISSUE TITLE
Could not find matching type for schema: {'type': ['null', 'string']}

### ISSUE THREAD

**Issue by xgodon** [wolverdude/GenSON#35]
the following : 

```
from genson import SchemaBuilder
import json

builder = SchemaBuilder()
builder2 = SchemaBuilder()

builder.add_object(
    {
        "main": "du texte",
        "deux": "oui"
        
        
    }
)
a = json.loads('{"main": null,"deux": "oui"}')
builder.add_object(a)

builder.add_object(
    {
        "main": {
            "a": "un",
            "b": "deux"
        },
        "deux": "oui"

    }
)

builder2.add_schema(builder)
e = builder2.to_json(indent=2)
print (e)
```

results in an error : 
genson.schema.node.SchemaGenerationError: Could not find matching type for schema: {'type': ['null', 'string']}

**Comment by wolverdude** [comment]
Got it. I think I know where that error is coming from. I'm about to go on vacation, but if it's urgent, I can try to fix it today. Otherwise, it'll have to wait at least a week.

**Comment by xgodon** [comment]
it's not urgent, don’t sweat it :)
thank you for your concern.

**Comment by xgodon** [comment]
note : i have a similar error for : 
a = json.loads('{"main": 9,"deux": "oui"}')

error :
genson.schema.node.SchemaGenerationError: Could not find matching type for schema: {'type': ['integer', 'string']}

**Comment by xgodon** [comment]
Any progress? :) It would be wonderful if i could make my demo work next week.

**Comment by wolverdude** [comment]
Sounds like this is finally urgent. Fortunately I'm back from vacation. I've been swamped so far, but I'll see what I can do about it tomorrow.

The source of the problem seems to be that `SchemaNode.to_schema` has logic for combining multiple `SchemaGenerator`s into a single schema, but `SchemaNode.add_schema` has no logic to do the inverse. For some reason I've never run into this error before. Thanks for catching it!

I'm hoping that I can get some headway on this tomorrow, but it does require a minor refactor that touches other code pending release in the next minor version. I'll see if I can disentangle it enough to release this as a patch, but no guarantees. It may have to wait for the next minor version which is still a couple weeks out optimistically.

**Comment by xgodon** [comment]
thanks !

Is there a reason for using "type": [...] and "AnyOf": ...?
Maybe using only AnyOf would be simpler, from a code perspective, but also from a user perspective.

**Comment by wolverdude** [comment]
Possibly, except that it's part of the JSON-Schema spec, so GenSON has to be able to deal with it anyway. Since it already has all the logic to generate type lists, there's no reason to rip that out.

**Comment by wolverdude** [comment]
Well, you're in luck. It turns out I was wrong, GenSON already has logic for parsing `anyOf`. The problem was that it failed to parse recursively. It ended up being a one-line fix. I still need to do comprehensive testing and ensure the docs are all up to date, but I should be able to release the fix tonight.

**Comment by wolverdude** [comment]
[version 1.1.0](https://pypi.org/project/genson/1.1.0/) is now live

**Comment by xgodon** [comment]
Thanks!
