### ISSUE TITLE
How to get only content from schema ?

### ISSUE THREAD

**Issue by Yawan-1** [wolverdude/GenSON#61]
I am trying to get only content from the schema. But when I try to access it like

````
builder.to_schema().content
````
then it keep says
> AttributeError: 'str' object has no attribute 'content'

**Comment by wolverdude** [comment]
Hi Yawan!

`to_schema()` returns a dict, not an object, so you have to access its data using square brackets (e.g. `builder.to_schema()["content"]`). That said, there is no `content` keyword in JSON-Schema that I'm aware of, so I'm not sure what you're asking for. Perhaps you want to get the schema for the `content` property in the original object? If so, then you'll need to do something like this:

```
builder.to_schema()["properties"]["content"]
```

If that's not what you mean by "content", then please specify. I'll go ahead and close this issue now, since it isn't a problem with GenSON's features.
