### ISSUE TITLE
Push latest version to PyPI

### ISSUE THREAD

**Issue by jdayton3** [wolverdude/GenSON#74]
The [last version of GenSON available on PyPI is 1.2.2](https://pypi.org/project/genson/), which was pushed from 6bf083488de2804c3ff5bb03b05761ff31fac30c. The latest version, [1.3.0](https://github.com/wolverdude/GenSON/blob/master/HISTORY.rst#130), has some nice features like compatibility with Python 3.9 and better error messages, and it would be great to have it available via pip install!

Happy to submit a PR if this is something that can be done with code, though it seems like the repo may just be [missing the 1.3.0 tag](https://github.com/wolverdude/GenSON/tags).

(For context, I came to the repo because I ran `genson $(big_list_of_files)`, it failed with a json parsing error but didn't tell me which file it was in, and it took some extra debugging to figure it out. So I wanted to contribute an enhancement to print the name of the file, but that already exists! Just not in PyPI yet. Thanks for a super useful & well documented package!)

**Comment by wolverdude** [comment]
Hey, sorry for the slow reply. I just had a kid and am a bit backlogged. TBH, I've tried to release 1.3 a couple of times but got bogged down. It's been long enough since my last attempt that I don't remember why, but I have some time this week to get to this, so I'll see if I can actually make it work this time. If I find I'm getting bogged down again, I'll document the blockers here so the community has a chance to help out. Who knows, maybe pull #76 is already addressing some of those.

**Comment by jdayton3** [comment]
No worries! Congrats on the new family member! Parenthood is the best, but it can definitely be a lot 😃 I'll watch here for any ways I can help with this.

**Comment by wolverdude** [comment]
[GenSON 1.3.0](https://pypi.org/project/genson/1.3.0) is released!

I proceeded manually this time just to get it done. I'm still looking into the automated process in PR #76.
